name=FlareDom
version=1.0.0
author=Moaaz
maintainer=Moaaz
sentence=HTML UI Framework for ESP8266/ESP32
paragraph=Build dynamic dashboards and interfaces using C++ components.
category=Display
url=https://github.com/moaaz/FlareDom
architectures=*
