name=FlareDom
version=1.1.0
author=Moaaz
maintainer=Moaaz
sentence=HTML UI Framework for ESP8266/ESP32
paragraph=Build dynamic dashboards and interfaces using C++ components. Includes Button, Table, Input, Navbar, ProgressBar, Badge, AlertBox, Switch, Footer, Container, ThemeManager, LiveValue, Animation and more.
category=Display
url=https://github.com/Moaaz-i/FlareDom
architectures=*
