name=FlareDom
version=1.2.0
author=Moaaz
maintainer=Moaaz
sentence=Asynchronous HTML UI Framework for ESP8266/ESP32
paragraph=Build dynamic, asynchronous dashboards using C++ components, ThemeManager, LiveValue, Animations, and WebSockets. Powered by ESPAsyncWebServer.
category=Display
url=https://github.com/Moaaz-i/FlareDom
architectures=*
depends=ESPAsyncWebServer, ESPAsyncTCP, AsyncTCP
